"""Fixed-pipeline CL baselines (B1 FBCSP+sLDA, B2 BandPower+sLDA) on STEW + WAUC.

Phase C of the model-development plan. Runs the two locked CL baselines per the
2x2 evaluation design (spec: ``design-doc/ccb-formulation.md`` §2.7):

    Baseline B1: thesis.baselines.fbcsp.FBCSP
        - 9-band FBCSP feature pipeline (4–8, 8–12, …, 36–40 Hz)
        - shrinkage LDA classifier
        - Cross-paradigm consistency check: does the MI-derived
          machinery transfer to cognitive load?

    Baseline B2: thesis.baselines.bandpower_cl.BandPowerCL
        - Per-channel log-band-power in θ / α / β
        - Channel-role-aware derived aggregates (frontal-θ, parietal-α,
          frontal-α asymmetry, engagement index)
        - shrinkage LDA classifier (same as B1)
        - Domain-specific CL baseline; isolates feature-pipeline effect.

Output: ``results/fixed_baseline_cl.csv`` with one row per
``(dataset, baseline, subject, fold, seed)``. A summary
``results/fixed_baseline_cl.md`` is generated by a follow-up
``scripts/summarize_fixed_baselines_cl.py`` (not in this commit;
the summary can also be regenerated from the CSV by hand for now).

Examples::

    # Default: both datasets, both baselines, 5-fold CV, single seed.
    PYTHONPATH=src .venv/bin/python scripts/run_fixed_baselines_cl.py

    # Smoke run on a few subjects.
    PYTHONPATH=src .venv/bin/python scripts/run_fixed_baselines_cl.py \\
        --subjects-stew 1,2,3 --subjects-wauc 1,2,3 --n-folds 1 \\
        --output results/fixed_baseline_cl_smoke.csv

    # Multi-seed sweep (5 seeds × 5 folds per subject per baseline).
    PYTHONPATH=src .venv/bin/python scripts/run_fixed_baselines_cl.py \\
        --seeds 0,1,2,3,42

Requires data/STEW/ and data/WAUC/process/ to be populated. Run
``make stew-check`` and ``make wauc-check`` first.
"""

from __future__ import annotations

from pathlib import Path

import mne
import numpy as np
import pandas as pd
import typer
from rich.console import Console
from rich.progress import track

from thesis.baselines.bandpower_cl import BandPowerCL
from thesis.baselines.fbcsp import FBCSP
from thesis.data import SubjectData
from thesis.data.stew_load import STEW_CHANNEL_ROLES, load_stew
from thesis.data.wauc_load import WAUC_CHANNEL_ROLES, load_wauc
from thesis.metrics import compute_metrics
from thesis.protocols import within_subject_cv

# Silence MNE's per-band CSP covariance-estimation chatter.
mne.set_log_level("WARNING")


def _build_baseline(name: str, *, sfreq: float, channel_roles: dict[str, list[int]] | None):
    """Construct the requested baseline. ``channel_roles`` consumed by B2 only."""
    if name == "fbcsp":
        return FBCSP(sfreq=sfreq)
    if name == "bandpower":
        return BandPowerCL(sfreq=sfreq, channel_roles=channel_roles)
    raise ValueError(f"unknown baseline name: {name!r}")


def _eval_one_subject(
    data: SubjectData,
    *,
    baseline_name: str,
    channel_roles: dict[str, list[int]] | None,
    n_folds: int,
    seeds: list[int],
    dataset_label: str,
) -> list[dict]:
    """Run one (subject × baseline) over folds × seeds; return per-eval rows."""
    rows: list[dict] = []
    for seed in seeds:
        # within_subject_cv yields up to 5 folds; take the first n_folds.
        splits = list(within_subject_cv(data, n_splits=5, seed=seed))[:n_folds]
        for fold_i, split in enumerate(splits):
            clf = _build_baseline(baseline_name, sfreq=data.sfreq, channel_roles=channel_roles)
            clf.fit(data.X[split.train_idx], data.y[split.train_idx])
            y_hat = clf.predict(data.X[split.test_idx])
            m = compute_metrics(data.y[split.test_idx], y_hat)
            rows.append(
                {
                    "dataset": dataset_label,
                    "baseline": baseline_name,
                    "subject": data.subject,
                    "fold": fold_i,
                    "seed": seed,
                    "kappa": float(m.kappa),
                    "accuracy": float(m.accuracy),
                    "n_train": int(len(split.train_idx)),
                    "n_test": int(m.n_trials),
                    "n_channels": int(data.n_channels),
                }
            )
    return rows


def _process_dataset(
    data_list: list[SubjectData],
    *,
    dataset_label: str,
    channel_roles: dict[str, list[int]] | None,
    baselines: list[str],
    n_folds: int,
    seeds: list[int],
    console: Console,
) -> list[dict]:
    rows: list[dict] = []
    for baseline_name in baselines:
        roles = channel_roles if baseline_name == "bandpower" else None
        desc = f"{dataset_label} × {baseline_name}"
        for data in track(data_list, description=desc, console=console):
            try:
                rows += _eval_one_subject(
                    data,
                    baseline_name=baseline_name,
                    channel_roles=roles,
                    n_folds=n_folds,
                    seeds=seeds,
                    dataset_label=dataset_label,
                )
            except Exception as exc:
                console.log(
                    f"[red]✗ {dataset_label} S{data.subject} {baseline_name} failed: {exc}[/red]"
                )
                rows.append(
                    {
                        "dataset": dataset_label,
                        "baseline": baseline_name,
                        "subject": data.subject,
                        "fold": -1,
                        "seed": -1,
                        "kappa": float("nan"),
                        "accuracy": float("nan"),
                        "n_train": 0,
                        "n_test": 0,
                        "n_channels": int(data.n_channels),
                        "error": str(exc),
                    }
                )
    return rows


def _parse_csv_int(s: str) -> list[int]:
    return [int(x.strip()) for x in s.split(",") if x.strip()]


def _parse_csv_str(s: str) -> list[str]:
    return [x.strip() for x in s.split(",") if x.strip()]


def main(
    datasets: str = typer.Option(
        "stew,wauc",
        help="Datasets to run: comma-separated from 'stew', 'wauc'.",
    ),
    baselines: str = typer.Option(
        "fbcsp,bandpower",
        help="Baselines to run: comma-separated from 'fbcsp', 'bandpower'.",
    ),
    subjects_stew: str = typer.Option(
        "all", help="Comma-separated STEW subject IDs (1..48, omitting 5/24/42), or 'all'."
    ),
    subjects_wauc: str = typer.Option(
        "all", help="Comma-separated WAUC filesystem IDs (1..48, omitting 28), or 'all'."
    ),
    n_folds: int = typer.Option(5, help="Within-subject CV folds (max 5)."),
    seeds: str = typer.Option("42", help="Comma-separated seeds. Default single seed."),
    output: Path = typer.Option(
        Path("results/fixed_baseline_cl.csv"),
        help="Output CSV path (per (dataset, baseline, subject, fold, seed)).",
    ),
) -> None:
    console = Console()

    dataset_list = _parse_csv_str(datasets)
    baseline_list = _parse_csv_str(baselines)
    seed_list = _parse_csv_int(seeds)
    stew_filter = None if subjects_stew == "all" else _parse_csv_int(subjects_stew)
    wauc_filter = None if subjects_wauc == "all" else _parse_csv_int(subjects_wauc)

    for ds in dataset_list:
        if ds not in {"stew", "wauc"}:
            console.print(f"[red]Unknown dataset {ds!r}; skipping.[/red]")
    for b in baseline_list:
        if b not in {"fbcsp", "bandpower"}:
            console.print(f"[red]Unknown baseline {b!r}; skipping.[/red]")

    rows: list[dict] = []

    if "stew" in dataset_list:
        console.log(f"Loading STEW subjects={stew_filter or 'all'} …")
        stew_data = load_stew(subjects=stew_filter)
        console.log(f"  → {len(stew_data)} STEW subjects loaded.")
        rows += _process_dataset(
            stew_data,
            dataset_label="STEW",
            channel_roles=STEW_CHANNEL_ROLES,
            baselines=baseline_list,
            n_folds=n_folds,
            seeds=seed_list,
            console=console,
        )

    if "wauc" in dataset_list:
        console.log(f"Loading WAUC subjects={wauc_filter or 'all'} …")
        wauc_data = load_wauc(subjects=wauc_filter)
        console.log(f"  → {len(wauc_data)} WAUC subjects loaded.")
        rows += _process_dataset(
            wauc_data,
            dataset_label="WAUC",
            channel_roles=WAUC_CHANNEL_ROLES,
            baselines=baseline_list,
            n_folds=n_folds,
            seeds=seed_list,
            console=console,
        )

    if not rows:
        console.print("[red]No rows generated. Check arguments and data availability.[/red]")
        raise typer.Exit(code=1)

    df = pd.DataFrame(rows)
    output.parent.mkdir(parents=True, exist_ok=True)
    df.to_csv(output, index=False)
    console.log(f"Saved {len(df)} rows → {output}")

    # Quick aggregate summary.
    summary = (
        df.dropna(subset=["kappa"])
        .groupby(["dataset", "baseline"])["kappa"]
        .agg(["mean", "std", "count"])
        .round(4)
    )
    console.rule("Mean κ per (dataset, baseline)")
    console.print(summary)
    console.rule("Mean accuracy per (dataset, baseline)")
    acc_summary = (
        df.dropna(subset=["accuracy"])
        .groupby(["dataset", "baseline"])["accuracy"]
        .agg(["mean", "std", "count"])
        .round(4)
    )
    console.print(acc_summary)

    console.print()
    console.print("[bold]Published reference baselines:[/bold]")
    console.print("  STEW (Lim 2018, SVR + NCA, 3-class):      κ = 0.46, accuracy = 0.69")
    console.print("  WAUC (Albuquerque 2020):                  reference κ TBV (verify in paper)")


if __name__ == "__main__":
    typer.run(main)
